//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.MVC.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _LayoutAdmin_nl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _LayoutAdmin_nl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.MVC.Resources.Views.Shared._LayoutAdmin.nl", typeof(_LayoutAdmin_nl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voeg een begeleider toe.
        /// </summary>
        internal static string Begeleider {
            get {
                return ResourceManager.GetString("Begeleider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak nieuwe flow aan.
        /// </summary>
        internal static string Flow {
            get {
                return ResourceManager.GetString("Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beheer gebruikers.
        /// </summary>
        internal static string Gebruikers {
            get {
                return ResourceManager.GetString("Gebruikers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingelogd als.
        /// </summary>
        internal static string Ingelogd {
            get {
                return ResourceManager.GetString("Ingelogd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggen.
        /// </summary>
        internal static string Ingloggen {
            get {
                return ResourceManager.GetString("Ingloggen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht van projecten.
        /// </summary>
        internal static string Overzicht {
            get {
                return ResourceManager.GetString("Overzicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak subplatform.
        /// </summary>
        internal static string Subplatform {
            get {
                return ResourceManager.GetString("Subplatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitloggen.
        /// </summary>
        internal static string Uitloggen {
            get {
                return ResourceManager.GetString("Uitloggen", resourceCulture);
            }
        }
    }
}
